"""empty

修订 ID: 46327b837dd8
父修订: e6460fccaf90
创建时间: 2023-10-12 15:32:47.496268

"""

from __future__ import annotations

from collections.abc import Sequence

revision: str = "46327b837dd8"
down_revision: str | Sequence[str] | None = "e6460fccaf90"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
