"""uninfo_id_not_none

迁移 ID: 6fbd51070a37
父迁移: cf3967d7f72f
创建时间: 2024-11-29 16:14:04.998527

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6fbd51070a37"
down_revision: str | Sequence[str] | None = "cf3967d7f72f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "uninfo_persist_id", existing_type=sa.INTEGER(), nullable=False
        )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "uninfo_persist_id", existing_type=sa.INTEGER(), nullable=True
        )
    # ### end Alembic commands ###
