"""ob12

Revision ID: 7228a3a08576
Revises: 2cad88d938f1
Create Date: 2023-01-16 17:15:05.640599

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlmodel import Session, select

from nonebot_plugin_chatrecorder import plugin_config
from nonebot_plugin_chatrecorder.model import MessageRecord

# revision identifiers, used by Alembic.
revision = "7228a3a08576"
down_revision = "2cad88d938f1"
branch_labels = None
depends_on = None


def set_default_value():
    with Session(op.get_bind()) as session:
        select_statement = select(MessageRecord)
        result = session.exec(select_statement)
        for row in result:
            row.bot_type = "OneBot V11"
            row.bot_id = plugin_config.chatrecorder_record_migration_bot_id
            session.add(row)
        session.commit()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "nonebot_plugin_chatrecorder_messagerecord",
        sa.Column("bot_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "nonebot_plugin_chatrecorder_messagerecord",
        sa.Column("bot_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "nonebot_plugin_chatrecorder_messagerecord",
        sa.Column("guild_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "nonebot_plugin_chatrecorder_messagerecord",
        sa.Column("channel_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    set_default_value()
    op.alter_column(
        "nonebot_plugin_chatrecorder_messagerecord",
        "bot_type",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "nonebot_plugin_chatrecorder_messagerecord",
        "bot_id",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("nonebot_plugin_chatrecorder_messagerecord", "channel_id")
    op.drop_column("nonebot_plugin_chatrecorder_messagerecord", "guild_id")
    op.drop_column("nonebot_plugin_chatrecorder_messagerecord", "bot_id")
    op.drop_column("nonebot_plugin_chatrecorder_messagerecord", "bot_type")
    # ### end Alembic commands ###
