"""add_uninfo_id

迁移 ID: 9d1364fbfb76
父迁移: 0f0a7bc40f3c
创建时间: 2024-11-29 16:03:02.247266

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9d1364fbfb76"
down_revision: str | Sequence[str] | None = "0f0a7bc40f3c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("uninfo_persist_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.drop_column("uninfo_persist_id")
    # ### end Alembic commands ###
