"""rename_uninfo_id

迁移 ID: a8fc25d97828
父迁移: b50d3f3f0443
创建时间: 2024-11-29 16:33:52.649715

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a8fc25d97828"
down_revision: str | Sequence[str] | None = "b50d3f3f0443"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "uninfo_persist_id",
            existing_type=sa.INTEGER(),
            nullable=False,
            new_column_name="session_persist_id",
        )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.alter_column(
            "session_persist_id",
            existing_type=sa.INTEGER(),
            nullable=False,
            new_column_name="uninfo_persist_id",
        )
    # ### end Alembic commands ###
