"""drop_session_id

迁移 ID: b50d3f3f0443
父迁移: 6fbd51070a37
创建时间: 2024-11-29 16:17:08.773782

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "b50d3f3f0443"
down_revision: str | Sequence[str] | None = "6fbd51070a37"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.drop_column("session_persist_id")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.add_column(
            sa.Column("session_persist_id", sa.INTEGER(), nullable=False)
        )
    # ### end Alembic commands ###
