"""fill_uninfo_id

迁移 ID: cf3967d7f72f
父迁移: 9d1364fbfb76
创建时间: 2024-11-29 16:04:59.852195

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from nonebot.log import logger
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session

revision: str = "cf3967d7f72f"
down_revision: str | Sequence[str] | None = "9d1364fbfb76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = "14175fde8186"


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    Base = automap_base()
    Base.prepare(autoload_with=conn)
    MessageRecord = Base.classes.nonebot_plugin_chatrecorder_messagerecord

    with Session(conn) as db_session:
        count = db_session.query(MessageRecord).count()
        if count == 0:
            return

    try:
        from nonebot_session_to_uninfo import check_tables, get_id_map
    except ImportError:
        raise ValueError("请安装 `nonebot-session-to-uninfo` 以迁移数据")

    check_tables()

    logger.warning("chatrecorder: 正在迁移数据，请不要关闭程序...")

    with Session(conn) as db_session:
        session_ids = list(
            db_session.scalars(sa.select(MessageRecord.session_persist_id)).all()
        )

    id_map = get_id_map(session_ids)

    with Session(conn) as db_session:
        for session_id, uninfo_id in id_map.items():
            db_session.execute(
                sa.update(MessageRecord)
                .where(MessageRecord.session_persist_id == session_id)
                .values(uninfo_persist_id=uninfo_id)
            )
        db_session.commit()

    logger.warning("chatrecorder: 数据迁移完成！")
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
