"""foreignkey

Revision ID: de6827ead8fe
Revises: 9bca28bcb998
Create Date: 2023-07-23 12:25:35.568101

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de6827ead8fe"
down_revision = "9bca28bcb998"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.add_column(sa.Column("session_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "foreignkey_session_id",
            "nonebot_plugin_session_sessionmodel",
            ["session_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "nonebot_plugin_chatrecorder_messagerecord", schema=None
    ) as batch_op:
        batch_op.drop_constraint("foreignkey_session_id", type_="foreignkey")
        batch_op.drop_column("session_id")

    # ### end Alembic commands ###
