"""init_db

迁移 ID: ea78280f71da
父迁移:
创建时间: 2024-11-30 13:10:23.110088

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ea78280f71da"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("nonebot_plugin_chatrecorder_v2",)
depends_on: str | Sequence[str] | None = "14175fde8186"


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_chatrecorder_messagerecord_v2",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_persist_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=255), nullable=False),
        sa.Column("message", sa.JSON(), nullable=False),
        sa.Column("plain_text", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_nonebot_plugin_chatrecorder_messagerecord_v2")
        ),
        info={"bind_key": "nonebot_plugin_chatrecorder_v2"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_chatrecorder_messagerecord_v2")
    # ### end Alembic commands ###
